// <auto-generated />
namespace SpaceSchedule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class smallUpdateLaunch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(smallUpdateLaunch));
        
        string IMigrationMetadata.Id
        {
            get { return "202206040655162_smallUpdateLaunch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
